var lang = {
	tr: {
		index: 'Anasayfa',
		partners: 'Partnerler',
		contact: 'İletişim',
		work: 'İş Paketleri',
		events: 'Etkinlikler-Haberler',
		documents: 'Dökümanlar',
		course: 'Eğitim Modülleri',
		education: 'EĞİTİM VE EĞİTİM ORGANİZASYONU',
		piece1: 'Eğitim için',
		piece2: 'Yaratıcı Çözümler',
		training:"EĞİTİM MODÜLLERİ",
		aile1: 'Aile içi İletişim',
		madde: 'Madde Bağımlılığında Bilinmesi Gerekenler ve Korunma Yolları',
		kendini:'Kendini Tanıma ve Anlama Yolları',
		com:'İletişim ve Önemi',
		azaltma:'Madde Kullanımını Azaltma veya Bırakma Yolları',
		ergenlik:'Ergenlik Çağı Sorunları ve Ergen İletişimi',
		problem:'Problem Çözme ve Başa Çıkma',
		maddeb:'Madde Bağımlısı Bireyle Görüşme Teknikleri',
		aile:'Aile içi Sorunlar ve Bağımlılık',
		bagimli:'Bağımlılık Yapan Maddeler ve Belirtileri',
		stres:'Stres ve Öfke Kontrolü',
		risk:'Madde Bağımlılığı Riskine Karşı Ebeveynlerin Bilmesi Gerekenler',
		serbest:'Madde Bağımlılığı Tedavisinde Serbest Zaman Etkinkinlikleri',
		davranis:'Problem Davranış Olarak Bağımlılıkla Baş Etme',
		onemi:'Madde Bağımlılığında Ailenin Önemi',
		teknik:'Madde Bağımlısı Birey ve Ailesi ile Görüşme Teknikleri',
		bakis:'Bağımlılığa pozitif psikoterapi bakışı',
		birey:'Madde Bağimlisi Olan Bireylerin Ailelerinin Eğitimi',
		partnertitle:'PARTNERLER',
		packages:'İŞ PAKETLERİ',
		atolye:'ATÖLYE',
		haber:'Haberler',
		event:'Etkinlikler',
		belgeler:'Belgeler',
		desc1:'Erasmus+ Programı kapsamında Avrupa Komisyonu tarafından desteklenmektedir. Ancak burada yer alan görüşlerden Avrupa Komisyonu ve Türkiye Ulusal Ajansı sorumlu tutulamaz.',
		project:'AİBÜ REHAB PROJESİ',
	},
	en: {
		index: 'Home',
		partners: 'Partners',
		contact: 'Contact Us',
		work: 'Work Packages',
		events: 'New & Events',
		documents: 'Documents',
		course: 'Training Course',
		education: 'EDUCATION & TRAINING ORGANIZATION',
		piece1: 'Inventive Solutions',
		piece2: 'for Education',
		training:'TRAINING COURSE',
		aile1: 'Communication in the Family',
		madde:'Drug addition and Needs to Know About it',
		kendini: 'The Way to Recognize and Manage the yourself',
		com:'Communication and Its Importance',
		azaltma:'Ways of Reducing or Abandoning Material Usage',
		ergenlik:'Teenager Issues and teenage Communication',
		problem:'Problem Solving and coping with  Techniques',
		maddeb:'Independent Interview Method',
		aile:'Family problems and addicted',
		bagimli:'Drug addiction and its Indications',
		stres:'Stress Management and Anger Management ',
		risk:'Parents Need to Know Against the Risk of Material addiction',
		serbest:'Free time management',
		davranis:'Techniques of coping with problem behavior ',
		onemi:'The Importance of Family in Substance Addiction',
		teknik:'Interviewing Techniques with Substance Addicts',
		bakis:'Positive psychotherapy approach to addiction',
		birey:'Training of Families of Individuals with Substance',
		partnertitle:'PARTNERS',
		packages:'WORK PACKAGES',
		atolye:'WORKSHOP',
		haber:'News',
		event:'Events',
		belgeler:'Documents',
		desc1:'“Funded by the Erasmus+ Program of the European Union. However, European Commission and Turkish National Agency cannot be held responsi­ble for any use which may be made of the information contained therein”',
		project:'REHAB PROJECT AIBU',
	},

	de: {
		index: 'Zuhause',
		partners: 'Partner',
		contact: 'Kontakt',
		work: 'Business-Pakete',
		events: 'Aktivitäten',
		documents: 'Unterlagen',
		course: 'Ausbildung',
		education: 'AUSBILDUNGS- UND AUSBILDUNGSORGANISATION',
		piece1: 'Innovative Lösungen',
		piece2: 'für die Bildung',
		training:'TRAININGSKURS',
		aile1: 'Kommunikation in der Familie',
		madde:'Drogensucht und Bedürfnisse darüber zu wissen',
		kendini: 'Der Weg, um sich selbst zu erkennen und zu verwalten',
		com:'Kommunikation und ihre Bedeutung',
		azaltma:'Möglichkeiten, die Materialnutzung zu reduzieren oder aufzugeben',
		ergenlik:'Jugendprobleme und Jugendkommunikation',
		problem:'Problemlösung und Umgang mit Techniken',
		maddeb:'Unabhängige Interviewmethode',
		aile:'Familienprobleme und süchtig',
		bagimli:'Drogenabhängigkeit und ihre Hinweise',
		stres:'Stressmanagement und Wutmanagement',
		risk:'Eltern müssen das Risiko einer materiellen Abhängigkeit kennen',
		serbest:'Freizeitmanagement',
		davranis:'Techniken zur Bewältigung des Problemverhaltens',
		onemi:'Die Bedeutung der Familie in der Substanzabhängigkeit',
		teknik:'Interviewtechniken mit Drogenabhängigen',
		bakis:'Positiver psychotherapeutischer Ansatz zur Sucht',
		birey:'Ausbildung von Familien von Personen mit Substanz',
		partnertitle:'PARTNER',
		packages:'ARBEITSPAKETE',
		atolye:'WERKSTATT',
		haber:'Nachrichten',
		event:'Veranstaltungen',
		belgeler:'Unterlagen',
	},
	esp:{
		index: 'Casa',
		partners: 'Socios',
		contact: 'Comunicación',
		work: 'Negocios',
		events: 'Actividades',
		documents: 'Documentos',
		course: 'curso',
		education: 'ORGANIZACIÓN DE EDUCACIÓN Y FORMACIÓN',
		piece1: 'Soluciones Inventivas ',
		piece2: 'para la Educación',
		training:'CURSO DE ENTRENAMIENTO',
		aile1: 'Comunicación en la familia',
		madde:'Adicción a las drogas y necesidades de saber al respecto',
		kendini: 'La forma de reconocer y gestionar el mismo',
		com:'La comunicación y su importancia.',
		azaltma:'Maneras de reducir o abandonar el uso de materiales',
		ergenlik:'Problemas de adolescentes y comunicación de adolescentes',
		problem:'Resolución de problemas y manejo de técnicas',
		maddeb:'Método de entrevista independiente',
		aile:'Problemas familiares y adictos.d',
		bagimli:'Adicción a las drogas y sus indicaciones',
		stres:'Manejo del estrés y manejo de la ira',
		risk:'Los padres necesitan saber contra el riesgo de adicción material',
		serbest:'Gestión del tiempo libre',
		davranis:'Técnicas de afrontamiento del comportamiento problemático',
		onemi:'La importancia de la familia en la adicción a sustancias',
		teknik:'Técnicas de entrevista con adictos a sustancias',
		bakis:'Enfoque psicoterapéutico positivo a la adicción',
		birey:'Entrenamiento de Familias de Individuos con Sustancia',
		partnertitle:'FOGONADURA',
		packages:'PAQUETES de TRABAJO',
		atolye:'TALLER',
		haber:'Noticias',
		event:'Eventos',
		belgeler:'Documentos',
	}


};
